# Generated by Django 5.1.2 on 2024-11-10 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='authorbook',
            name='contribution_date',
            field=models.DateField(null=True),
        ),
    ]
