# Generated by Django 5.1.2 on 2024-11-11 01:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_authorbook_contribution_summary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authorbook',
            name='contribution_summary',
        ),
        migrations.CreateModel(
            name='Contribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contribution_type', models.CharField(max_length=255)),
                ('is_primary_author', models.BooleanField(default=False)),
                ('contribution_date', models.DateTimeField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.author')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.book')),
            ],
        ),
    ]
