# Generated by Django 5.1.2 on 2024-11-11 03:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_authorbook_contribution_summary_contribution'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='authors',
        ),
        migrations.DeleteModel(
            name='AuthorBook',
        ),
    ]
