# Generated by Django 5.1.2 on 2024-11-11 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_authorbook_book_authors'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contribution',
        ),
    ]
