# Generated by Django 5.1.2 on 2024-11-11 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_delete_contribution'),
    ]

    operations = [
        migrations.AddField(
            model_name='authorbook',
            name='contribution_summary',
            field=models.TextField(default='No contribution summary'),
        ),
    ]
