# Generated by Django 5.1.2 on 2024-11-11 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_authorbook_contribution_summary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authorbook',
            name='contribution_summary',
        ),
    ]
