# Generated by Django 5.1.2 on 2024-11-11 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_authorbook_contribution_summary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='authors',
        ),
    ]
