# Generated by Django 5.1.2 on 2024-11-11 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_book_authors_contribution'),
    ]

    operations = [
        migrations.AddField(
            model_name='authorbook',
            name='contribution_summary',
            field=models.TextField(default='Default summary text'),
        ),
        migrations.DeleteModel(
            name='Contribution',
        ),
    ]
