# Generated by Django 5.1.2 on 2024-11-11 11:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_authorbook_contribution_summary_delete_contribution'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contribution_details', models.TextField()),
                ('contribution_date', models.DateField()),
                ('contribution_primary_author', models.BooleanField(default=False)),
                ('contribution_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributions', to='api.author')),
                ('contribution_book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributions', to='api.book')),
            ],
        ),
    ]
