# Generated by Django 5.1.1 on 2024-11-12 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_authorbook_contribution_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authorbook',
            name='contribution_type',
        ),
    ]
